### ISSUE TITLE
Update documentation to remove Jenkins references

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/solas#34]
When our move to GitLab is done, we should pull all Jenkins references from the documentation.

**Comment by DStorck** [comment]
solas-container https://github.com/samsung-cnct/solas-container/pull/25

**Comment by DStorck** [comment]
solas-chart https://github.com/samsung-cnct/solas-chart/pull/21

**Comment by coffeepac** [comment]
all three solas repos do not reference jenkinsfiles.
